# Generated by Django 4.2.7 on 2023-11-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='capas_livro/')),
                ('estoque', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
