# Generated by Django 4.2 on 2023-12-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelalugar',
            options={'verbose_name': 'Aluguel', 'verbose_name_plural': 'Alugueis'},
        ),
        migrations.AlterModelOptions(
            name='modelanalise',
            options={'verbose_name': 'Análise', 'verbose_name_plural': 'Análises'},
        ),
        migrations.AlterModelOptions(
            name='modelfavoritos',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AlterModelOptions(
            name='modellivro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AddField(
            model_name='modelusuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='management.modellivro'),
        ),
    ]
